version: "3.8"

networks:
  exchange:

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exchange
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - exchange

  auth_service:
    build:
      context: ./services/auth_service
    container_name: auth_service
    restart: always
    env_file:
      - ./services/auth_service/.env
    depends_on:
      - db
    ports:
      - "8001:8001"
    volumes:
      - ./services/auth_service:/auth_service
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    networks:
      - exchange

    redis_celery:
      image: redis:alpine
      container_name: redis_celery
      restart: always
      ports:
        - "6379:6379"
    
    celery_worker:
    build: .
    command: celery -A celery_worker worker --loglevel=info
    depends_on:
      - redis_celery
      - auth_service
    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A celery_worker beat --loglevel=info
    depends_on:
      - redis_celery
      - celery_worker
    

volumes:
  postgres_data:
