version: "3.8"

networks:
  exchange:

services:
  db:
    image: postgres:15
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - exchange
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - exchange

  auth_service:
    build:
      context: ./services/auth_service
    container_name: auth_service
    restart: always
    env_file:
      - ./services/auth_service/.env
    depends_on:
      - db
    ports:
      - "8001:8001"
    volumes:
      - ./services/auth_service:/auth_service
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8001 --reload"
    networks:
      - exchange

  wallet_service:
    build:
      context: ./services/wallet_service
    container_name: wallet_service
    restart: always
    env_file:
      - ./services/wallet_service/.env
    depends_on:
      - db
    ports:
      - "8002:8002"
    volumes:
      - ./services/wallet_service:/wallet_service
    command: >
      sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8002 --reload"
    networks:
      - exchange

  redis_celery:
    image: redis:alpine
    container_name: redis_celery
    restart: always
    ports:
      - "6379:6379"
    networks:
      - exchange
  
  celery_worker:
    build:
      context: ./services/auth_service
    command: celery -A app.tasks.worker_config worker --loglevel=info
    depends_on:
      - redis_celery
    env_file:
      - .env
    volumes:
      - ./services/auth_service:/auth_service
    networks:
      - exchange

  celery_beat:
    build:
      context: ./services/auth_service
    command: celery -A app.tasks.worker_config beat --loglevel=info
    depends_on:
      - redis_celery
    volumes:
      - ./services/auth_service:/auth_service
    networks:
      - exchange

volumes:
  postgres_data:
