FROM python:3.11

# Устанавливаем зависимости для Cython и компиляции
RUN apt-get update && apt-get install -y build-essential gcc

WORKDIR /app

# Копируем зависимости и устанавливаем их
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем файлы проекта
COPY . .

# Собираем Cython-код
RUN python setup.py build_ext --inplace
# Запускаем код, указывая PYTHONPATH
CMD ["python", "-c", "import matching_engine; from matching_engine import consume_orders; import asyncio; asyncio.run(consume_orders())"]
