"""add order status

Revision ID: 6c29e526032b
Revises: deedb05b74fa
Create Date: 2025-03-17 06:25:11.851811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c29e526032b'
down_revision: Union[str, None] = 'deedb05b74fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('status', sa.Enum('NEW', 'FILLED', 'CANCELED', 'PENDING', 'REJECTED', name='statusorder'), nullable=False, server_default=sa.text("'NEW'")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'status')
    # ### end Alembic commands ###
