"""add ticker table

Revision ID: deedb05b74fa
Revises: fd51f6953466
Create Date: 2025-03-14 12:28:13.530014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deedb05b74fa'
down_revision: Union[str, None] = 'fd51f6953466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ticker_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'orders', 'tickers', ['ticker_id'], ['id'])
    op.drop_column('orders', 'ticker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('ticker', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_column('orders', 'ticker_id')
    # ### end Alembic commands ###
