"""Initial migration

Revision ID: 38c1d85f1166
Revises: 
Create Date: 2025-05-17 14:36:28.729928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38c1d85f1166'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker')
    )
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVATE', 'DEACTIVATE', name='walletstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_wallet_user_id', 'wallets', ['user_id'], unique=False)
    op.create_index(op.f('ix_wallets_user_id'), 'wallets', ['user_id'], unique=False)
    op.create_table('wallet_asset_balances',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('locked', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('wallet_id', 'asset_id')
    )
    op.create_index('idx_wallet_assets_wallet_asset', 'wallet_asset_balances', ['wallet_id', 'asset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_wallet_assets_wallet_asset', table_name='wallet_asset_balances')
    op.drop_table('wallet_asset_balances')
    op.drop_index(op.f('ix_wallets_user_id'), table_name='wallets')
    op.drop_index('idx_wallet_user_id', table_name='wallets')
    op.drop_table('wallets')
    op.drop_table('assets')
    # ### end Alembic commands ###
